### ISSUE TITLE
Refactor service parameters to use flag

### ISSUE THREAD

**Issue by andreagrandi** [aliveim/aliveim-service#15]
Parameters should be passed using **flag** library: https://gobyexample.com/command-line-flags

p.s: I'm working on this ticket already

**Comment by alessio** [comment]
I thought it was not necessary as we need just 2 parameters and they can very well be supplied as positional parameters.

**Comment by andreagrandi** [comment]
Better use standard libraries, expecially if we are parsing an input. Not a problem, I will do it as an exercise to resume writing a bit of Go

**Comment by alessio** [comment]
:+1:
