### ISSUE TITLE
Error parsing request after PR merged

### ISSUE THREAD

**Issue by andreagrandi** [aliveim/aliveim-service#8]
Hi @alessio I just noticed that after I merged your PR, manually calling the tests I get this error:

```
(go:aliveim) ➜  aliveim-service git:(master) ✗ go test
Start timer...
Sleep 100 ms...
Sleep 300 ms...
2016/02/07 11:43:12 DeviceID: abc123 expired!
Printed after device expiration
2016/02/07 11:43:12 DeviceID: abc123, Timeout: 300
2016/02/07 11:43:12 DeviceID: abc123, Timeout: 300
2016/02/07 11:43:12 ERROR: Couldn't parse request -- EOF
PASS
ok      _/Users/andrea/Projects/aliveim-service 0.423s
```

while if I checkout the old commit, I get the expected behaviour:

```
(go:aliveim) ➜  aliveim-service git:(41f526d) ✗ go test
Start timer...
Sleep 100 ms...
Sleep 300 ms...
2016/02/07 11:43:49 DeviceID: abc123 expired!
Printed after device expiration
2016/02/07 11:43:49 DeviceID: abc123, Timeout: 300
2016/02/07 11:43:49 DeviceID: abc123, Timeout: 300
PASS
ok      _/Users/andrea/Projects/aliveim-service 0.425s
```

I'm not sure why the CI didn't catch this.. probably I didn't write the test in the correct way. We need to investigate this.

p.s: keep in mind that only the API component will **POST** a request on the microservice, so unless we have a bug on the API, we request will never be malformed.

**Comment by alessio** [comment]
It should be OK, It prints the error message as expected, in fact the tests tries to reproduce a malformed request :)

**Comment by alessio** [comment]
Actually there's a mistake in the response handling of receipt of bad requests. It should return a 400 code. I'm on it.
